#!/usr/bin/env bash
# Bash script to configure Nginx for a 301 redirection

# Install Nginx if not already installed (you can reuse the installation script from task 1)
sudo apt-get update
sudo apt-get install -y nginx

# Create a new configuration file for the redirection
echo "location /redirect_me {
    return 301 https://www.youtube.com/watch?v=QH2-TGU1wu4;
}" | sudo tee /etc/nginx/sites-available/redirect_me > /dev/null

# Create a symbolic link to the sites-enabled directory
sudo ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled

# Remove the default configuration
sudo rm -f /etc/nginx/sites-enabled/default

# Restart Nginx to apply the changes
sudo service nginx restart

# Display a message indicating the completion of the setup
echo "Nginx configured for 301 redirection from /redirect_me to https://www/youtube.com/watch?v=QH2-TGUlwu4"
