#!/usr/bin/env bash
# Customizing a 404-error_page

# Updating Packages before performing installations
sudo apt-get update
sudo apt-get install -y nginx

# Creating an index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# Performing a "moved permanently redirection" (301)
sudo sed -i 's/# server_names_hash_bucket_size.*/server_names_hash_bucket_size 64;/' /etc/nginx/nginx.conf
echo "server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html index.htm;
        server_name _;
        location / {
                try_files $uri $uri/ =404;
        }
}" | sudo tee /etc/nginx/sites-available/default > /dev/null


# Creating a 404 Custom error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null

# Custom HTTP response header
sudo sed -i '/listen 80 default_server;/a \        add_header X-Served-By $HOSTNAME;' /etc/nginx/sites-available/default

# Testing configurations for syntax errors
sudo nginx -t

# restart nginx after implementing changes
sudo service nginx restart
