#!/usr/bin/env bash
# Configure Nginx to listen on port 80
service nginx stop
if ! grep -q "listen 80;" /etc/nginx/sites-available/default; then
    sed -i 's/^\(\s*listen\s*\)[[:digit:]]\+;/\180;/g' /etc/nginx/sites-available/default
    service nginx start
    sleep 1 # Give some time for Nginx to start
    if curl -s -I http://localhost:80 | head -n 1 | grep -q "HTTP/1.1 200 OK"; then
        echo "Nginx is running and returning HTTP 200 on port 80."
    else
        echo "Nginx is not running or not returning HTTP 200 on port 80."
    fi
else
    echo "Nginx is already configured to listen on port 80."
fi
