#!/usr/bin/env bash
# This script changes the IP resolution of localhost and facebook.com

# Backup the original hosts file
sudo cp /etc/hosts /etc/hosts.bak

sed -i 's/127.*$/127.0.0.2 localhost\n8.8.8.8 facebook.com/' ~/hosts.new

# Display the modified hosts file
cat /etc/hosts

