#!/usr/bin/env bash
# This script configures Nginx to run as the nginx user and listen on port 8080

# Update the Nginx configuration to run as nginx user
sed -i 's/^user .*;$/user nginx;/' /etc/nginx/nginx.conf

# Update Nginx configuration to listen on port 8080
sed -i 's/^listen\s*80\s;$/listen 8080;/g' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
service nginx restart
