#!/usr/bin/env bash
# Configure Nginx to run as the nginx user and listen on port 8080

sed -i 's/^user.*;$/user nginx/' /etc/nginx/nginx.conf
sed -i 's/^listen\s*80\s*;$/listen 8080/' /etc/nginx/sites-available/default
service nginx restart
